name: GitHub Org Member Manage Action
description: Manage GitHub org memberships in a declarative way.
branding:
  icon: 'at-sign'  
  color: 'green'

# Inputs are provided as ENVIRONMENT VARIABLES WITH INPUT_ prefix (e.g., INPUT_MEMBERS_FILEPATH).
# See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs.
inputs:
  gh_token:
    description: GitHub Token with admin:org access
    required: true
    default: ""
  members_filepath:
    description: Filepath to members.yaml.
    required: true
    default: members.yaml
  dry_run:
    description: Does not update any memberships but just fetch only
    required: false
  mode:
    description: >
      There are 2 modes (sync|write).
      "sync" mode will try to update memberships.
      "write" mode will just fetch data and write YAML in `members_filepath`.
    required: false
    default: sync

runs:
  using: docker
  image: Dockerfile
