name: GitHub Org Member Manage Action
description: Manage GitHub org memberships in a declarative way.

# Inputs are provided as ENVIRONMENT VARIABLES WITH INPUT_ prefix (e.g., INPUT_MEMBERS_FILEPATH).
# See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs.
inputs:
  gh_token:
    description: GitHub Token with admin:org access
    required: true
    default: ""
  members_filepath:
    description: Filepath to members.yaml.
    required: true
    default: members.yaml
runs:
  using: docker
  image: Dockerfile
